# Generated by Django 5.2.2 on 2025-06-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinesiologia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='fecha',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='hora',
            new_name='Hora',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='observaciones',
            new_name='Observaciones',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='paciente',
            new_name='Paciente',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='profesional',
            new_name='Profesional',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellido',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='dni',
            new_name='DNI',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='Fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='tel',
            new_name='Tel',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='apellido',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='especialidad',
            new_name='Especialidad',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='tel',
            new_name='Tel',
        ),
        migrations.AddField(
            model_name='profesional',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
    ]
