# Generated by Django 5.2.2 on 2025-06-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinesiologia', '0002_rename_fecha_consulta_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_arterial', models.CharField(max_length=20)),
                ('movimientos_activos', models.TextField()),
                ('movimientos_pasivos', models.TextField()),
                ('test_neurologicos', models.TextField()),
                ('test_ortopedicos', models.TextField()),
                ('test_neurodinamicos', models.TextField()),
                ('palpacion', models.TextField()),
                ('test_adicionales', models.TextField()),
                ('observaciones_clinicas', models.TextField()),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_fisico', to='kinesiologia.consulta')),
            ],
        ),
    ]
