# Generated by Django 5.2.2 on 2025-06-26 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinesiologia', '0003_examenfisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('Profesional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinesiologia.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='kinesiologia.paciente')),
            ],
        ),
    ]
